exclude: |
  (?x)(
      ^bin/.*                    # bin/ at repo root
    | ^third_party/.*            # third_party/ at repo root
    | .*\.(bat|BAT|dat|gtp)$     # .bat and a few similar
    | .*\.(epw|stat|audit)$      # EnergyPlus specific files
  )
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    # We exclude these because ddy/epw are treated as immutable, and the idf/imf etc are formatted by Transition tool probably
    exclude: '.*\.(idf|imf|rvi|mvi|epw|ddy)$'
  - id: check-merge-conflict
  - id: check-yaml

- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 6.1.0
  hooks:
  - id: isort
