name: Compute checksums

on:
  push:
    branches: [ checksums ]

  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name for which to run it (eg: v22.1.0). If not specified, defaults to the latest release'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Needed permission to upload the release asset
      contents: write

    steps:

    - name: Download binaries
      shell: bash
      run: |
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-CentOS7.9.2009-x86_64.tar.gz" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-Ubuntu20.04-x86_64.run" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-Ubuntu20.04-x86_64.sh" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-Ubuntu20.04-x86_64.tar.gz" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-Ubuntu22.04-arm64.tar.gz" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-Ubuntu22.04-x86_64.run" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-Ubuntu22.04-x86_64.sh" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Linux-Ubuntu22.04-x86_64.tar.gz" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Windows-i386.exe" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Windows-i386.zip" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Windows-x86_64-HardenedRuntime.exe" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Windows-x86_64-HardenedRuntime.zip" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Windows-x86_64.exe" >> download_lists.txt
        echo "https://github.com/NREL/EnergyPlus/releases/download/v23.2.0/EnergyPlus-23.2.0-7636e6b3e9-Windows-x86_64.zip" >> download_lists.txt

        echo "Found the following assets"
        cat download_lists.txt
        echo "Downloading all via aria"
        aria2c --input-file download_lists.txt -j $(nproc)
        echo "Files in current directory:"
        ls

    - name: Upload Sums to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'EnergyPlus-23.2.0*'
        tag: v23.2.0-WithMacStaticLibs
        overwrite: false
        file_glob: true
